name: tasks
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.2.0
  dart_jsonwebtoken: ^3.2.0
  json_annotation: ^4.9.0
  orm: ^2.1.2
  build_runner: ^2.4.14
  json_serializable: ^6.9.5

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^7.0.0
